"""m20 initial trust core schema

Revision ID: b31a01dd94f2
Revises:
Create Date: 2026-08-24 01:53:11.006750

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b31a01dd94f2"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_events",
        sa.Column("event_id", sa.String(length=64), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("actor", sa.String(length=64), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("intent_id", sa.String(length=64), nullable=True),
        sa.Column("checkout_id", sa.String(length=64), nullable=True),
        sa.Column("decision_id", sa.String(length=64), nullable=True),
        sa.Column("ticket_id", sa.String(length=64), nullable=True),
        sa.Column("intent_hash", sa.String(length=128), nullable=True),
        sa.Column("checkout_hash", sa.String(length=128), nullable=True),
        sa.Column("reason_codes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("previous_event_hash", sa.String(length=128), nullable=True),
        sa.Column("current_event_hash", sa.String(length=128), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("event_id"),
        sa.UniqueConstraint("current_event_hash", name="uq_audit_current_hash"),
    )
    op.create_index("ix_audit_intent_id", "audit_events", ["intent_id"], unique=False)
    op.create_index("ix_audit_timestamp", "audit_events", ["timestamp"], unique=False)
    op.execute(
        """
        CREATE OR REPLACE FUNCTION prevent_audit_mutation() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION 'audit_events is append-only; UPDATE/DELETE forbidden';
            RETURN NULL;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_audit_no_update BEFORE UPDATE OR DELETE ON audit_events
        FOR EACH ROW EXECUTE FUNCTION prevent_audit_mutation();
        """
    )
    op.create_table(
        "intent_contracts",
        sa.Column("intent_id", sa.String(length=64), nullable=False),
        sa.Column("principal_id", sa.String(length=64), nullable=False),
        sa.Column("agent_id", sa.String(length=64), nullable=False),
        sa.Column("authorization_generation", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("allowed_merchant_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("allowed_product_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("allowed_categories", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("brand_restriction", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("condition_restriction", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("currency", sa.String(length=8), nullable=False),
        sa.Column("max_total_minor", sa.BigInteger(), nullable=False),
        sa.Column("aggregate_budget_minor", sa.BigInteger(), nullable=False),
        sa.Column("max_quantity", sa.Integer(), nullable=False),
        sa.Column("recurring_allowed", sa.Boolean(), nullable=False),
        sa.Column("approval_threshold_minor", sa.BigInteger(), nullable=False),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("authorized_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("intent_id"),
    )
    op.create_index(
        op.f("ix_intent_contracts_agent_id"), "intent_contracts", ["agent_id"], unique=False
    )
    op.create_index(
        op.f("ix_intent_contracts_principal_id"), "intent_contracts", ["principal_id"], unique=False
    )
    op.create_table(
        "merchants",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "authorization_spend",
        sa.Column("intent_id", sa.String(length=64), nullable=False),
        sa.Column("authorized_minor", sa.BigInteger(), nullable=False),
        sa.Column("reserved_minor", sa.BigInteger(), nullable=False),
        sa.Column("committed_minor", sa.BigInteger(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("authorized_minor >= 0", name="ck_spend_authorized_nonneg"),
        sa.CheckConstraint("committed_minor >= 0", name="ck_spend_committed_nonneg"),
        sa.CheckConstraint("reserved_minor >= 0", name="ck_spend_reserved_nonneg"),
        sa.ForeignKeyConstraint(["intent_id"], ["intent_contracts.intent_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("intent_id"),
    )
    op.create_table(
        "checkouts",
        sa.Column("checkout_id", sa.String(length=64), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("merchant_id", sa.String(length=64), nullable=False),
        sa.Column("line_items", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("tax_minor", sa.BigInteger(), nullable=False),
        sa.Column("shipping_minor", sa.BigInteger(), nullable=False),
        sa.Column("fees_minor", sa.BigInteger(), nullable=False),
        sa.Column("provided_total_minor", sa.BigInteger(), nullable=False),
        sa.Column("computed_total_minor", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.String(length=8), nullable=False),
        sa.Column("subscription_terms", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
        ),
        sa.PrimaryKeyConstraint("checkout_id"),
    )
    op.create_index("ix_checkouts_merchant_id", "checkouts", ["merchant_id"], unique=False)
    op.create_table(
        "products",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("merchant_id", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("brand", sa.String(length=100), nullable=True),
        sa.Column("category", sa.String(length=100), nullable=False),
        sa.Column("condition", sa.String(length=32), nullable=False),
        sa.Column("price_minor", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.String(length=8), nullable=False),
        sa.Column("shipping_minor", sa.BigInteger(), nullable=False),
        sa.Column("tax_minor", sa.BigInteger(), nullable=False),
        sa.Column("fees_minor", sa.BigInteger(), nullable=False),
        sa.Column("recurring", sa.Boolean(), nullable=False),
        sa.Column("recurring_frequency", sa.String(length=32), nullable=True),
        sa.Column("image_url", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["merchant_id"], ["merchants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_products_brand", "products", ["brand"], unique=False)
    op.create_index("ix_products_category", "products", ["category"], unique=False)
    op.create_index("ix_products_merchant_id", "products", ["merchant_id"], unique=False)
    op.create_table(
        "decisions",
        sa.Column("decision_id", sa.String(length=64), nullable=False),
        sa.Column("intent_id", sa.String(length=64), nullable=False),
        sa.Column("checkout_id", sa.String(length=64), nullable=False),
        sa.Column("intent_generation", sa.Integer(), nullable=False),
        sa.Column("checkout_hash", sa.String(length=128), nullable=False),
        sa.Column("policy_version", sa.String(length=64), nullable=False),
        sa.Column("decision", sa.String(length=16), nullable=False),
        sa.Column("reason_codes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("rule_results", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["checkout_id"],
            ["checkouts.checkout_id"],
        ),
        sa.ForeignKeyConstraint(
            ["intent_id"],
            ["intent_contracts.intent_id"],
        ),
        sa.PrimaryKeyConstraint("decision_id"),
    )
    op.create_index("ix_decisions_checkout_hash", "decisions", ["checkout_hash"], unique=False)
    op.create_index("ix_decisions_intent_id", "decisions", ["intent_id"], unique=False)
    op.create_table(
        "execution_tickets",
        sa.Column("ticket_id", sa.String(length=64), nullable=False),
        sa.Column("principal_id", sa.String(length=64), nullable=False),
        sa.Column("agent_id", sa.String(length=64), nullable=False),
        sa.Column("intent_id", sa.String(length=64), nullable=False),
        sa.Column("intent_hash", sa.String(length=128), nullable=False),
        sa.Column("authorization_generation", sa.Integer(), nullable=False),
        sa.Column("checkout_hash", sa.String(length=128), nullable=False),
        sa.Column("checkout_revision", sa.Integer(), nullable=False),
        sa.Column("merchant_id", sa.String(length=64), nullable=False),
        sa.Column("amount_minor", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.String(length=8), nullable=False),
        sa.Column("decision_id", sa.String(length=64), nullable=False),
        sa.Column("policy_version", sa.String(length=64), nullable=False),
        sa.Column("nonce", sa.String(length=128), nullable=False),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["decision_id"],
            ["decisions.decision_id"],
        ),
        sa.PrimaryKeyConstraint("ticket_id"),
        sa.UniqueConstraint("nonce", name="uq_ticket_nonce"),
    )
    op.create_index("ix_tickets_intent_id", "execution_tickets", ["intent_id"], unique=False)
    op.create_index("ix_tickets_principal_id", "execution_tickets", ["principal_id"], unique=False)
    op.create_table(
        "execution_attempts",
        sa.Column("execution_attempt_id", sa.String(length=64), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("ticket_id", sa.String(length=64), nullable=False),
        sa.Column("intent_id", sa.String(length=64), nullable=False),
        sa.Column("checkout_id", sa.String(length=64), nullable=False),
        sa.Column("amount_minor", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.String(length=8), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("provider_reference", sa.String(length=128), nullable=True),
        sa.Column("error_code", sa.String(length=128), nullable=True),
        sa.Column("provider_event", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["ticket_id"],
            ["execution_tickets.ticket_id"],
        ),
        sa.PrimaryKeyConstraint("execution_attempt_id"),
        sa.UniqueConstraint("idempotency_key", name="uq_attempt_idempotency"),
    )
    op.create_index("ix_attempts_intent_id", "execution_attempts", ["intent_id"], unique=False)
    op.create_index("ix_attempts_state", "execution_attempts", ["state"], unique=False)
    op.create_index("ix_attempts_ticket_id", "execution_attempts", ["ticket_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_attempts_ticket_id", table_name="execution_attempts")
    op.drop_index("ix_attempts_state", table_name="execution_attempts")
    op.drop_index("ix_attempts_intent_id", table_name="execution_attempts")
    op.drop_table("execution_attempts")
    op.drop_index("ix_tickets_principal_id", table_name="execution_tickets")
    op.drop_index("ix_tickets_intent_id", table_name="execution_tickets")
    op.drop_table("execution_tickets")
    op.drop_index("ix_decisions_intent_id", table_name="decisions")
    op.drop_index("ix_decisions_checkout_hash", table_name="decisions")
    op.drop_table("decisions")
    op.drop_index("ix_products_merchant_id", table_name="products")
    op.drop_index("ix_products_category", table_name="products")
    op.drop_index("ix_products_brand", table_name="products")
    op.drop_table("products")
    op.drop_index("ix_checkouts_merchant_id", table_name="checkouts")
    op.drop_table("checkouts")
    op.drop_table("authorization_spend")
    op.drop_table("merchants")
    op.drop_index(op.f("ix_intent_contracts_principal_id"), table_name="intent_contracts")
    op.drop_index(op.f("ix_intent_contracts_agent_id"), table_name="intent_contracts")
    op.drop_table("intent_contracts")
    op.execute("DROP TRIGGER IF EXISTS trg_audit_no_update ON audit_events")
    op.execute("DROP FUNCTION IF EXISTS prevent_audit_mutation()")
    op.drop_index("ix_audit_timestamp", table_name="audit_events")
    op.drop_index("ix_audit_intent_id", table_name="audit_events")
    op.drop_table("audit_events")
    # ### end Alembic commands ###
